---
title: JackieTFitness
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: "Super Cool Awesome   \nSlogan About Awesomness   \n"
owner: Stephen Mitchell
first_published: 2018
email: spmitchell10@gmail.com
baseurl: ''
url: http://yourdomain.com
social:
  twitter: https://twitter.com/spmitchell_
  github: https://github.com/spmitchell10
  linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/<username>
  google-plus-square: https://plus.google.com/u/0/+<username>
markdown: kramdown
